services:
  postgres:
    image: postgres:16-alpine
    container_name: weather-postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: weather_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: